[build]
  command = "CI=false npm ci --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
